# ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ Kube Prometheus Stack Configuration                                                                              │
# │ For more options, refer to official documentation:                                                               │
# │ https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml           │
# └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
kube-prometheus-stack:
# ┌─────────────────────────────────────────────────────────────────────────────┐
# │   Default Rules Configuration                                               │
# │   - Create default rules for monitoring the cluster                         │
# │   - Disable rules for unreachable components                                │
# └─────────────────────────────────────────────────────────────────────────────┘
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeScheduler: false


# ┌──────────────────────────────────────────────────────────────────────────┐
# │ Set custom ACN approved ports for these services                         │
# └──────────────────────────────────────────────────────────────────────────┘
  alertmanager:
    service:
      port: 15010
# ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │   Component Scraping Configuration                                                                                  │
# │   Disable component scraping for the kube controller manager, etcd, and kube-scheduler                              │
# │   These components are not reachable on EKS                                                                         │
# └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeSchedulerAlerting:
    enabled: false
  kubeSchedulerRecording:
    enabled: false
# ┌─────────────────────────────────────────────────────────────────────────────┐
# │   Prometheus Configuration                                                  │
# └─────────────────────────────────────────────────────────────────────────────┘
  prometheus:
    service:
      port: 15017
    prometheusSpec:
      # Prometheus StorageSpec for persistent data on AWS EBS
      # ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
      storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    kubelet:
      serviceMonitor:
        relabelings:
          - action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: kubernetes_node
        metricRelabelings:
          - action: replace
            sourceLabels:
              - node
            targetLabel: instance
# ┌──────────────────────────────────────────────────────────────────────────┐
# │ Prometheus Operator Configuration                                        │
# └──────────────────────────────────────────────────────────────────────────┘
  prometheusOperator:
    enabled: true
    # Not using cert-manager
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false
# ┌─────────────────────────────────────────────────────────────────────────────┐
# │   Grafana Configuration                                                     │
# │   Disable Grafana                                                           │
# └─────────────────────────────────────────────────────────────────────────────┘
  grafana:
    enabled: false
