{{- if and (.Values.karpenter) (.Values.karpenter.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: {{ .Values.argoProject | default "default" }}
  revisionHistoryLimit: 3
  source:
    repoURL: "{{ .Values.repoUrl }}"
    path: services/helm/karpenter
    targetRevision: "{{ .Values.targetRevision }}"
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: karpenter.serviceAccount.name
          value: "{{ .Values.karpenter.serviceAccountName }}"
        - name: karpenter.settings.clusterName
          value: "{{ .Values.clusterName }}"
        - name: karpenter.settings.clusterEndpoint
          value: "{{ .Values.clusterEndpoint }}"
        - name: karpenter.settings.interruptionQueue
          value: "{{ .Values.karpenter.interruptionQueueName }}"
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace="{{ .Values.karpenter.createNamespace }}"
      - Replace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  {{- end -}}
